Network Simulator: Node Class Reference
Node Class Reference abstract
Abstract Node class.
#include <node.hpp>
Public Member Functions
Node (std::string name)
Construct a new Node object.
virtual NodeType GetType () const =0
Virtual function. Get the Node type.
std::string GetName () const
Get the Name object.
std::string GetIPAddress () const
Get the IPAddress object.
std::vector< Node * > GetAdjacents () const
Get the Adjacents Nodes of this object.
void SetIPAddress (std::string &address)
Sets random generated IP Address to tis Node.
void Connect (Node *&other)
Connects this Node with another node which is added to adjacent list.
void SendPacket (Packet p, Node *node_to_send)
Sends packet to next Node,.
virtual void ReceivePacket (Packet p)=0
Virtual method for receiving packet. Implemented differently in EndHost and Router.
void SetRunningState (bool val)
Set the Running State to true or false. This is used to control the packet flow from DataflowScenario class. If all packets are sent, the other nodes will be notified.
bool operator== (const Node &other) const
If Nodes have same names or IP addresses, they are equal.
Protected Attributes
bool is_running_
Private Attributes
std::string name_
std::string IP_address_
std::vector< Node * > adjacents_
Detailed Description
Abstract Node class.
Other network nodes derive from this class (EndHost, Router)
Constructor & Destructor Documentation
Node()
Node::Node (std::string name) inline
Construct a new Node object.
Parameters
name Name given by user, for example "PC-1", "Router-5" or "John's PC"
In addition, constructor initializes the IP address, Simulator will take care that it's unique
: name_(name), is_running_(false) {}
~Node()
virtual Node::~Node () inline virtual
{}
Member Function Documentation
Connect()
void Node::Connect (Node *& other)
Connects this Node with another node which is added to adjacent list.
Parameters
other EndHost or Router
{
    adjacents_.push_back(other);
}
Referenced by Simulator::AddLink().
GetAdjacents()
std::vector< Node * > Node::GetAdjacents () const
Get the Adjacents Nodes of this object.
Returns
std::list<Node *>
Needed for the FindPath method
{
    return adjacents_;
}
GetIPAddress()
std::string Node::GetIPAddress () const
Get the IPAddress object.
Returns
std::string IP address, generated by Simulator class
{
    return IP_address_;
}
Referenced by operator==().
GetName()
std::string Node::GetName () const
Get the Name object.
Returns
std::string Name given to the node by user
{
    return name_;
}
Referenced by DataflowScenario::FindPath(), DataflowScenario::IsReachable(), operator==(), and DataflowScenario::PrintSummary().
GetType()
virtual NodeType Node::GetType () const pure virtual
Virtual function. Get the Node type.
Returns
NodeType
Implemented in EndHost, and Router.
operator==()
bool Node::operator== (const Node & other) const
If Nodes have same names or IP addresses, they are equal.
Parameters
other
Returns
true
false
{
    if (this->GetName() == other.GetName() && this->GetIPAddress() == other.GetIPAddress())
    {
        return true;
    }
    return false;
}
ReceivePacket()
virtual void Node::ReceivePacket (Packet p) pure virtual
Virtual method for receiving packet. Implemented differently in EndHost and Router.
Parameters
p Packet object
Implemented in EndHost, and Router.
Referenced by SendPacket().
SendPacket()
void Node::SendPacket (Packet p, Node * node_to_send)
Sends packet to next Node,.
Parameters
p Packet to be sent
node_to_send EndHost or Router
{
    node_to_send->ReceivePacket(p);
}
Referenced by Router::PacketFlowThread(), and DataflowScenario::PacketSendingThread().
SetIPAddress()
void Node::SetIPAddress (std::string & address)
Sets random generated IP Address to tis Node.
Parameters
address IP in format XXX.XXX.XXX.XXX
{
    IP_address_ = address;
}
Referenced by Simulator::CreateNode().
SetRunningState()
void Node::SetRunningState (bool val)
Set the Running State to true or false. This is used to control the packet flow from DataflowScenario class. If all packets are sent, the other nodes will be notified.
Parameters
val true or false
{
    is_running_ = val;
}
The documentation for this class was generated from the following files:
src/backend/node.hpp
src/backend/node.cpp