Network Simulator: DataflowScenario Class Reference
DataflowScenario Class Reference
class DataflowScenario
#include <dataflowscenario.hpp>
Public Member Functions
DataflowScenario (EndHost *s, EndHost *e, size_t size, std::list< Node * > all_nodes, std::list< Link * > all_links)
Construct a new Dataflow Scenario object.
size_t GetSize () const
Get the size of data to be sent.
EndHost * GetStartNode () const
Get the Start Node object.
EndHost * GetEndNode () const
Get the End Node object.
Link * GetLinkBetweenNodes (Node *node1, Node *node2)
Get the Link Between Nodes.
std::list< Packet > GenerateData ()
Generates list of packets based on the size.
bool IsValid ()
Checks if this scenario is valid for run.
Summary Run ()
Runs this scenario:
Private Member Functions
std::vector< Node * > FindPath ()
Finds shortest path from start node to end node (if exists)
bool IsReachable (std::map< std::string, std::vector< Node * > > &graph, Node *src, Node *dest, std::map< std::string, bool > &discovered, std::vector< Node * > &path)
Helper function for FindPath. Function performs DFS traversal in a directed graph to find the complete path between source and destination nodes.
std::string PrintWholeRoute (std::vector< Node * > nodes, std::vector< Link * > links)
Prints and returns the whole route in format (endhost) –link_speed– (router) –link_speed– (endhost)
void PacketSendingThread (std::list< Packet > packets, Node *next_node, size_t speed, std::vector< Node * > path)
Thread that sends one packet at the time from the list that was created from bigger data unit (data_packet_size_)
void PacketTransferThread (Router *sending_node, Node *next_node, size_t speed)
std::thread GetThread (Router *r, Node *n2, size_t s)
Get the Packet Transfer Thread object.
void Terminate (std::vector< Node * > path)
Terminates the current simulation, that is, notifys the nodes in the path that no more packets are to be transferred and they can stop waiting.
void PrintSummary (std::vector< Router * > routers, std::list< Packet > packets)
Utility function for development purposes and to help testing.
Private Attributes
EndHost * start_node_
EndHost * end_node_
size_t data_packet_size_
std::list< Node * > all_nodes_
std::list< Link * > all_links_
const size_t MinNodeCount = 3
Packet_MTU mtu_type = Ethernet
Detailed Description
class DataflowScenario
Description:
DataflowScenario represents a scenario made by user where data is sent from EndHost (start) to EndHost (end). User can define which node will sent data to where and what is the data size These scenarios will be stored to Simulator class that finally runs all the scenarios
(EndHost start) —link— (Router r) —link— (EndHost end)
Constructor & Destructor Documentation
DataflowScenario()
DataflowScenario::DataflowScenario (EndHost * s, EndHost * e, size_t size, std::list< Node * > all_nodes, std::list< Link * > all_links) inline
Construct a new Dataflow Scenario object.
Parameters
s Start node
e End Node
size Data size MB (megabyte)
The DataflowScenario class has a constructor that takes in the start node (EndHost), end node (EndHost), and size of the data (size_t)
        : start_node_(s), end_node_(e), data_packet_size_(size), all_nodes_(all_nodes), all_links_(all_links) {}
Member Function Documentation
FindPath()
std::vector< Node * > DataflowScenario::FindPath () private
Finds shortest path from start node to end node (if exists)
Returns
std::list<Node>
Before the scenario can begin its actions, the route needs to be calculated. This method needs to find all the nodes between the start and end. If the end node is not reachable, this scenario is unvalid.
If the nodes are connected like this:
(EndHost start) —link— (Router r) —link— (EndHost end)
FindPath will return list: [start, r, end]
{
    std::vector<Node *> path;
    std::map<std::string, std::vector<Node *>> graph;
    std::map<std::string, bool> visited;
    // init adjacent list and visited list
    for (auto node : all_nodes_)
    {
        graph.insert({node->GetName(),
                      node->GetAdjacents()});
        visited.insert({node->GetName(), false});
    }
    if (IsReachable(graph, start_node_, end_node_, visited, path))
    {
        //std::cout << "Path exists from node " << start_node_.GetName() << " to node " << end_node_.GetName() << std::endl;
    }
    else
    {
        std::cout << "No path exists between nodes " << start_node_->GetName() << " and " << end_node_->GetName() << std::endl;
    }
    return path;
}
Referenced by IsValid(), and Run().
GenerateData()
std::list< Packet > DataflowScenario::GenerateData ()
Generates list of packets based on the size.
Currently the system is using the default value of the Ethernet MTU which is 1500 bytes / packet. Some bytes are reserved for the header. See Packet class for more information
Returns
std::list<Packet>
{
    int max_size = mtu_type - Packet::GetHeaderLength();                  // max bytes that packet can take
    auto num_of_whole_packets = (data_packet_size_ * 1000000) / max_size; // MB = million
    auto remaining_length = data_packet_size_ % max_size;
    std::list<Packet> result;
    auto seqnum = 1;
    auto id = GenerateRandomPacketId();
    for (size_t i = 0; i < num_of_whole_packets; i++)
    {
        result.push_back(Packet(id, max_size, seqnum));
        seqnum++;
    }
    result.push_back(Packet(id, remaining_length, seqnum));
    return result;
}
Referenced by Run().
GetEndNode()
EndHost * DataflowScenario::GetEndNode () const
Get the End Node object.
Returns
EndHost
{
    return end_node_;
}
GetLinkBetweenNodes()
Link * DataflowScenario::GetLinkBetweenNodes (Node * node1, Node * node2)
Get the Link Between Nodes.
Parameters
node1
node2
Returns
Link*
{
    for (auto link : all_links_)
    {
        if (link->IsConnected(node1, node2))
        {
            return link;
        }
    }
    return nullptr;
}
Referenced by Run().
GetSize()
size_t DataflowScenario::GetSize () const
Get the size of data to be sent.
Returns
size_t
{
    return data_packet_size_;
}
GetStartNode()
EndHost * DataflowScenario::GetStartNode () const
Get the Start Node object.
Returns
EndHost
{
    return start_node_;
}
GetThread()
std::thread DataflowScenario::GetThread (Router * r, Node * n2, size_t s) private
Get the Packet Transfer Thread object.
Parameters
n1 starting node
n2 next node on the path
s link speed between these nodes
Returns
std::thread
{
    return std::thread(&DataflowScenario::PacketTransferThread, this, r, n2, s);
}
Referenced by Run().
IsReachable()
bool DataflowScenario::IsReachable (std::map< std::string, std::vector< Node * > > & graph, Node * src, Node * dest, std::map< std::string, bool > & discovered, std::vector< Node * > & path) private
Helper function for FindPath. Function performs DFS traversal in a directed graph to find the complete path between source and destination nodes.
Parameters
graph map of adjacent lists
src source Node (EndHost)
dest destination Node (EndHost)
discovered map of discovered nodes
path
Returns
true
false
{
    // mark the current node as discovered
    discovered[src->GetName()] = true;
    // include the current node in the path
    path.push_back(src);
    // if destination vertex is found
    if (*src == *dest)
    {
        return true;
    }
    // do for every edge (src, n)
    for (auto n : graph[src->GetName()])
    {
        // if 'n' is not yet discovered
        if (!discovered[n->GetName()])
        {
            if (IsReachable(graph, n, dest, discovered, path))
            {
                return true;
            }
        }
    }
    // backtrack: remove the current node from the path
    path.pop_back();
    // return false if destination vertex is not reachable from src
    return false;
}
Referenced by FindPath(), and IsReachable().
IsValid()
bool DataflowScenario::IsValid ()
Checks if this scenario is valid for run.
Returns
true
false
calls FindPath and checks if the end node can be reached from start node, the path also needs to be at least three nodes long, if not returns false, otherwise true
{
    auto nodes = FindPath();
    // If Path is shorter than minimum node count, it's not valid.
    if (nodes.size() < MinNodeCount)
    {
        return false;
    }
    auto iterator_start = nodes.begin();
    auto iterator_end = nodes.end();
    iterator_end--;
    auto start = *iterator_start;
    auto end = *iterator_end;
    if (iterator_start != nodes.end() && *start == *start_node_)
    {
        if (iterator_end != nodes.end() && *end == *end_node_)
        {
            return true;
        }
    }
    return false;
}
Referenced by Run().
PacketSendingThread()
void DataflowScenario::PacketSendingThread (std::list< Packet > packets, Node * next_node, size_t speed, std::vector< Node * > path) private
Thread that sends one packet at the time from the list that was created from bigger data unit (data_packet_size_)
Parameters
packets Packets to be sent
next_node The second node on this path
speed Link speed between the start_node_ and next node
path Whole path in this simulation. The method will call termination when all packets are sent
{
    auto trans_speed = speed * 10000; // 10 Kbps
    std::cout << "Started to send packets. Please wait... " << std::endl;
    int i = 1;
    while (packets.size() > 0)
    {
        auto packet = packets.front();
        auto size = packet.GetSize();
        double delay = (size * 8.0 / trans_speed) * 1000.0; // to Milliseconds
        // Wait ... simulate the time to transmit the packet
        std::this_thread::sleep_for(std::chrono::milliseconds((int)delay));
        // Send packet
        start_node_->SendPacket(packet, next_node);
        packets.pop_front();
        //std::cout << "packet sent " << i << std::endl;
        i++;
    }
    Terminate(path);
}
Referenced by Run().
PacketTransferThread()
void DataflowScenario::PacketTransferThread (Router * sending_node, Node * next_node, size_t speed) private
Parameters
sending_node Router that transfers data
next_node Next node after the router
speed Link speed between these nodes
{
    auto router = dynamic_cast<Router *>(sending_node);
    router->SetRunningState(true);
    router->PacketFlowThread(next_node, speed);
}
Referenced by GetThread().
PrintSummary()
void DataflowScenario::PrintSummary (std::vector< Router * > routers, std::list< Packet > packets) private
Utility function for development purposes and to help testing.
Parameters
routers Routers in the path
packets List of packets created in this scenario
end
{
    std::cout << "\n"
              << std::endl;
    std::cout << "************************************" << std::endl;
    std::cout << "******** Scenario finished *********" << std::endl;
    std::cout << "************************************\n"
              << std::endl;
    std::cout << "Summary:" << std::endl;
    std::cout << "  Number of packets sent by " << start_node_->GetName() << ": " << packets.size() << std::endl;
    std::cout << "  Number of packets received by " << end_node_->GetName() << ": " << end_node_->GetNumOfReceivedPackets() << std::endl;
    for (auto r : nodes)
    {
        std::cout << "  Packets dropped by " << r->GetName() << ": " << r->GetLostPackets() << std::endl;
    }
}
Referenced by Run().
PrintWholeRoute()
std::string DataflowScenario::PrintWholeRoute (std::vector< Node * > nodes, std::vector< Link * > links) private
Prints and returns the whole route in format (endhost) –link_speed– (router) –link_speed– (endhost)
Parameters
nodes Nodes in the current path
links Links in the current path
{
    std::string path = " ";
    for (size_t i = 0; i < nodes.size(); i++)
    {
        if (i >= nodes.size() - 1)
        {
            std::cout << "(" << nodes[i]->GetName() << ") " << std::endl;
            path += "(" + nodes[i]->GetName() + ")";
            break;
        }
        std::cout << "(" << nodes[i]->GetName() << ") ";
        std::cout << "--" << links[i]->GetTransmissionSpeed() << "-- ";
        path += "(" + nodes[i]->GetName() + ") --" + std::to_string(links[i]->GetTransmissionSpeed()) + "-- ";
    }
    return path;
}
Referenced by Run().
Run()
Summary DataflowScenario::Run ()
Runs this scenario:
If scenario is valid, the data will flow through route from FindPath
GenerateData is called which is creating a list of packets to be sent
Starting node starts sending packets through link to the next node on the route
Continues until all packets are sent
{
    std::cout << "************************************" << std::endl;
    std::cout << "******* Scenario is starting *******" << std::endl;
    std::cout << "************************************\n"
              << std::endl;
    if (IsValid())
    {
        auto path = FindPath();
        std::vector<Link *> links_in_path;
        for (size_t i = 0; i < path.size() - 1; i++)
        {
            links_in_path.push_back(GetLinkBetweenNodes(path[i], path[i + 1]));
        }
        std::string backgroun_info = " Dataflow path: \n";
        std::cout << "Dataflow path: " << std::endl;
        backgroun_info += PrintWholeRoute(path, links_in_path) + "\n\n";
        std::cout << std::endl;
        std::vector<Router *> routers;
        auto packets = GenerateData();
        backgroun_info += " Size of the original data: " + std::to_string(data_packet_size_) + " MB\n";
        backgroun_info += " Packet MTU = " + std::to_string((int)Ethernet) + " bytes\n";
        std::cout << "Size of the data to be sent: " << data_packet_size_ << " MB" << std::endl;
        std::cout << "Number of packets: " << packets.size() << " (Packet MTU = " << int(Ethernet) << " bytes)\n"
                  << std::endl;
        // Start timer
        auto start = std::chrono::high_resolution_clock::now();
        std::list<std::thread> threads;
        // Create thread for every router along the path, these nodes will be waiting for the packets to arrive
        for (size_t j = 1; j < path.size() - 1; j++)
        {
            auto router = dynamic_cast<Router *>(path[j]);
            auto link = GetLinkBetweenNodes(path[j], path[j + 1]);
            threads.push_back(GetThread(router, path[j + 1], link->GetTransmissionSpeed()));
            routers.push_back(router);
        }
        // This thread starts pushing the packets forward, the thread is detached to run as its own
        std::thread data_sending_thread(&DataflowScenario::PacketSendingThread, this, packets, path[1], links_in_path[0]->GetTransmissionSpeed(), path);
        data_sending_thread.detach();
        // Mainthread will wait for the other threads to finish before finishing. If there are
        // packets in the buffers, this will take a while
        for (auto &thr : threads)
        {
            thr.join();
        }
        // Stop time
        auto finish = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double> elapsed = finish - start;
        PrintSummary(routers, packets);
        return Summary(backgroun_info, elapsed, packets.size(), end_node_->GetNumOfReceivedPackets(), routers);
    }
    std::chrono::duration<double> e;
    return Summary("", e, 0, 0, std::vector<Router *>{});
}
Terminate()
void DataflowScenario::Terminate (std::vector< Node * > path) private
Terminates the current simulation, that is, notifys the nodes in the path that no more packets are to be transferred and they can stop waiting.
Parameters
path Path of nodes in this simulation
{
    for (auto n : path)
    {
        n->SetRunningState(false);
    }
}
Referenced by PacketSendingThread().
The documentation for this class was generated from the following files:
src/backend/dataflowscenario.hpp
src/backend/dataflowscenario.cpp